### ISSUE TITLE
preferences - max. write cycles

### ISSUE THREAD

**Issue by DIYLAB-DE** [samm-git/clock-controller-esp#8]
I'm a bit worried that the values saved every minute with "Preferences" could damage the ESP32.
Isn't the maximum write cycle approx. 100000x ?

**Comment by samm-git** [comment]
Technically I think we will never reach it. Data is stored on [NVS partition](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/nvs_flash.html) which I did big enough, so I hope that it is evenly distributed across it. As you can see - this repo is 4 years old and the clock is still working perfectly, including TZ changes, etc. IMO there is a chance that board will be obsoleted much faster compared to flash wear out, so I don't want to fix what is not broken.

The likely best option would be to add cheap i2c RTC to the device, so time would tick when the device is out of main power, and these RTCs usually have some battery-powered bytes that could be used to store physical clock status. But I am lazy enough to fix what is not broken :)
